- name: Launch Windows Attacker Instances
  ec2_instance:
    name: "ATTACKER-WIN"
    image_id: "{{ windows_ami_id }}"
    instance_type: "t2.micro"
    key_name: "{{ key_name }}"
    count: 1
    subnet_id: "{{ public_subnet_result.subnet.id }}"
    security_groups: ["{{ public_sg_result.group_id }}"]
    region: "{{ region }}"
    network:
      auto_assign_public_ip: true
      private_ip_address: "10.0.1.10"
    metadata_options:
      http_tokens: required
    aap_callback:
      windows: true
      set_password: "{{ attacker_win_password }}"
    wait: true
    wait_timeout: 600
  register: win_attack_result
  ignore_errors: true

- name: Launch Linux Attacker Instances
  ec2_instance:
    name: "ATTACKER-LIN"
    image_id: "{{ ubuntu_20_04_ami_id }}"
    instance_type: "t2.micro"
    key_name: "{{ key_name }}"
    count: 1
    subnet_id: "{{ public_subnet_result.subnet.id }}"
    security_groups: ["{{ public_sg_result.group_id }}"]
    region: "{{ region }}"
    network:
      auto_assign_public_ip: true
      private_ip_address: "10.0.1.20"
    metadata_options:
      http_tokens: required
  register: lin_attack_result
  ignore_errors: true

- debug:
    msg: "Windows Attacker Public IP is: {{ win_attack_result.instances[0].public_ip_address }}"

- debug:
    msg: "Ubuntu Attacker Public IP is: {{ lin_attack_result.instances[0].public_ip_address }}"
